# -*- coding: utf-8 -*-
"""Calorie_Estimation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGPC-O8hr1WTPM7QwTkGqHjDwG9J7D6t

# Install Packages
"""

!pip install -q fsspec==2023.1.0 datasets huggingface_hub

!pip install -q datasets huggingface_hub

import os
import random
import numpy as np
import matplotlib.pyplot as plt

"""# Authenticate with Hugging Face & Google Drive"""

from huggingface_hub import login
login(token="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")
from google.colab import drive
drive.mount('/content/drive')

"""# Load Data Set

# Data Set Link: https://huggingface.co/datasets/EduardoPacheco/FoodSeg103
"""

from datasets import load_dataset
dataset = load_dataset("EduardoPacheco/FoodSeg103")

print(dataset)
example = dataset["train"][0]
print(example.keys())
print(type(example["image"]))
print(type(example["label"]))

import matplotlib.pyplot as plt

img = example["image"]
mask = example["label"]
plt.figure(figsize=(8,4))
plt.subplot(1,2,1); plt.imshow(img); plt.title("Image"); plt.axis("off")
plt.subplot(1,2,2); plt.imshow(mask, cmap="tab20"); plt.title("Mask"); plt.axis("off")

print(dataset["train"].features)
print(dataset["validation"].features)

"""# Data Saving"""

drive_folder = '/content/drive/MyDrive/FoodSeg103'

if os.path.isdir(drive_folder) and os.listdir(drive_folder):
    print(f"Folder already exists and contains data:\n  {drive_folder}\nSkipping save.")
else:
    os.makedirs(drive_folder, exist_ok=True)
    dataset = load_dataset("EduardoPacheco/FoodSeg103")
    dataset.save_to_disk(drive_folder)
    print(f"Dataset successfully saved to:\n  {drive_folder}")

"""# Display Sample Images"""

n_samples = 3
indices = random.sample(range(len(dataset["train"])), n_samples)

# 3. Plot each image alongside its mask
for idx in indices:
    ex = dataset["train"][idx]
    img = np.array(ex["image"])
    mask = np.array(ex["label"])

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12,5))
    ax1.imshow(img)
    ax1.set_title(f"Image (ID={ex['id']})")
    ax1.axis("off")

    # use a qualitative colormap to show different classes
    ax2.imshow(mask, cmap="tab20", vmin=0, vmax=19)
    ax2.set_title(f"Mask (classes: {ex['classes_on_image']})")
    ax2.axis("off")

plt.tight_layout()
plt.show()

"""# Download the id to label mapping file


"""

from huggingface_hub import hf_hub_download
import json

mapping_file = hf_hub_download(repo_id="EduardoPacheco/FoodSeg103", filename="id2label.json", repo_type="dataset")
with open(mapping_file, "r") as f:
    id2label = json.load(f)

id2name = {int(k): v for k, v in id2label.items()}

print(f"Total defined classes (incl. background): {len(id2name)}")
print(f"Background class (ID=0): {id2name[0]}\n")


print("Sample mappings:")
for cls_id in range(5):
    print(f"  {cls_id}: {id2name[cls_id]}")

train_ids = set()
for cls_list in dataset["train"]["classes_on_image"]:
    train_ids.update(cls_list)

print(f"\nClasses present in train: {len(train_ids)} / {len(id2name)}")
missing = sorted(set(id2name.keys()) - train_ids)
print(f"Missing class IDs in train: {missing}")

from collections import Counter

cnt = Counter()
for cls_list in dataset["train"]["classes_on_image"]:
    cnt.update(set(cls_list))

for cls_id, freq in cnt.most_common(5):
    print(f"{id2name[cls_id]:<15s}: {freq} images")
for cls_id, freq in cnt.most_common()[-5:]:
    print(f"{id2name[cls_id]:<15s}: {freq} images")

"""# Top 10 most common classes"""

top10 = cnt.most_common(10)
classes = [id2name[cid] for cid, _ in top10]
counts = [count for _, count in top10]

plt.figure(figsize=(10, 6))
plt.bar(classes, counts)
plt.xticks(rotation=45, ha='right')
plt.ylabel("Number of Images")
plt.title("Top 10 Ingredient Classes by Image Count")
plt.tight_layout()
plt.show()

"""# Image Count per Ingredient Class (All 104 Classes)"""

all_ids = sorted(id2name.keys())
labels = [id2name[i] for i in all_ids]
counts = [cnt.get(i, 0) for i in all_ids]
plt.figure(figsize=(20, 6))
bars = plt.bar(labels, counts)
plt.xticks(rotation=90, fontsize=8)
plt.yticks(fontsize=10)
plt.xlabel("Ingredient Class", fontsize=12)
plt.ylabel("Number of Images", fontsize=12)
plt.title("Image Count per Ingredient Class (All 104 Classes)", fontsize=14)

# Add the count on top of each bar
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2.0, yval, int(yval), va='bottom', ha='center', fontsize=6) # add the count above the bar


plt.tight_layout()
plt.show()

"""# Calculate counts in different ranges"""

count_above_100 = sum(1 for count in counts if count > 100)
count_100_to_50 = sum(1 for count in counts if 50 <= count <= 100)
count_50_to_25 = sum(1 for count in counts if 25 <= count < 50)
count_25_to_10 = sum(1 for count in counts if 10 <= count < 25)
count_10_to_0 = sum(1 for count in counts if 0 <= count < 10)

print(f"Number of classes with image count > 100: {count_above_100}")
print(f"Number of classes with image count between 50 and 100 (inclusive): {count_100_to_50}")
print(f"Number of classes with image count between 25 and 50 (exclusive of 50): {count_50_to_25}")
print(f"Number of classes with image count between 10 and 25 (exclusive of 25): {count_25_to_10}")
print(f"Number of classes with image count between 0 and 10 (exclusive of 10): {count_10_to_0}")

# List class names for each category
classes_above_100 = [id2name[all_ids[i]] for i, count in enumerate(counts) if count > 100]
classes_100_to_50 = [id2name[all_ids[i]] for i, count in enumerate(counts) if 50 <= count <= 100]
classes_50_to_25 = [id2name[all_ids[i]] for i, count in enumerate(counts) if 25 <= count < 50]
classes_25_to_10 = [id2name[all_ids[i]] for i, count in enumerate(counts) if 10 <= count < 25]
classes_10_to_0 = [id2name[all_ids[i]] for i, count in enumerate(counts) if 0 <= count < 10]

print("\nClasses with image count > 100:")
print(classes_above_100)

print("\nClasses with image count between 50 and 100 (inclusive):")
print(classes_100_to_50)

print("\nClasses with image count between 25 and 50 (exclusive of 50):")
print(classes_50_to_25)

print("\nClasses with image count between 10 and 25 (exclusive of 25):")
print(classes_25_to_10)

print("\nClasses with image count between 0 and 10 (exclusive of 10):")
classes_10_to_0