# -*- coding: utf-8 -*-
"""segmodel-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QLXrMNdpYP587XccyuwNwL8fzGbKCsO_
"""

!pip install tensorflow
!pip install datasets
!pip install segmentation_models
!pip install tf-models-official
!pip install pydot graphviz

import tensorflow as tf

print("TensorFlow version:", tf.__version__)
gpus = tf.config.list_physical_devices('GPU')
print("GPUs found:", gpus)
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("Enabled memory growth on GPU.")
    except Exception as e:
        print("Could not set memory growth:", e)

import os, json, random, math
from typing import Tuple, List, Optional
from collections import Counter, defaultdict
import numpy as np
from tqdm import tqdm
from PIL import Image, ImageOps
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import img_to_array
from datasets import load_dataset
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
import torchvision.transforms.functional as TF
from torchvision.transforms import InterpolationMode, ColorJitter
import albumentations as A
from albumentations.pytorch import ToTensorV2
from transformers import SegformerForSemanticSegmentation
import torchvision.transforms.functional as TF
from torchvision.transforms import InterpolationMode, ColorJitter

from google.colab import drive
drive.mount('/content/drive')

"""# Config, paths, checks

"""

IMAGE_SIZE   = (512, 384)
BATCH_SIZE   = 4
NUM_WORKERS  = 2
SEED         = 1337

ROOT = "/content/drive/MyDrive/FoodSeg103_2"
IMG_DIR_TRAIN = f"{ROOT}/train"
IMG_DIR_VAL   = f"{ROOT}/validation"
MASK_DIR_TRAIN = f"{ROOT}/train_final"
MASK_DIR_VAL   = f"{ROOT}/validation_final"
ID2LABEL_PATH  = f"{ROOT}/id2label_final.json"

def check_path(p, kind="path"):
    ok = os.path.exists(p)
    print(f"{'Correct' if ok else 'Wrong'} {kind}: {p}")
    return ok

print("Checking dataset paths…")
_ = [
    check_path(IMG_DIR_TRAIN, "train images"),
    check_path(IMG_DIR_VAL,   "val images"),
    check_path(MASK_DIR_TRAIN,"train masks"),
    check_path(MASK_DIR_VAL,  "val masks"),
    check_path(ID2LABEL_PATH, "id2label json"),
]

# Load label map
with open(ID2LABEL_PATH, "r") as f:
    id2label = json.load(f)
id2label = {int(k): v for k, v in id2label.items()}
NUM_CLASSES = len(id2label)
print(f"Loaded {NUM_CLASSES} classes. Sample:", {k:id2label[k] for k in list(id2label)[:8]})

# Reproducibility
def set_seed(seed=SEED):
    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed)
    if torch.cuda.is_available(): torch.cuda.manual_seed_all(seed)
set_seed()

"""# Pair image and Mask

"""

from typing import List, Tuple

def pair_files(img_dir: str, mask_dir: str) -> List[Tuple[str, str]]:
    imgs = sorted([f for f in os.listdir(img_dir) if f.endswith(".jpg")])
    pairs, missing = [], 0
    for fn in imgs:
        mname = fn.replace("image", "label").replace(".jpg", ".png")
        ip = os.path.join(img_dir, fn)
        mp = os.path.join(mask_dir, mname)
        if os.path.isfile(mp): pairs.append((ip, mp))
        else: missing += 1
    if missing: print(f"{missing} masks missing for images in {img_dir}")
    return pairs

train_pairs = pair_files(IMG_DIR_TRAIN, MASK_DIR_TRAIN)
val_pairs   = pair_files(IMG_DIR_VAL,   MASK_DIR_VAL)

print(f"Found {len(train_pairs)} train pairs, {len(val_pairs)} val pairs.")
print("Example pair:\n  img :", train_pairs[0][0], "\n  mask:", train_pairs[0][1])

def peek_mask_ids(pairs, k=3):
    import random
    picks = random.sample(pairs, min(k, len(pairs)))
    for i, (_, mpath) in enumerate(picks, 1):
        arr = np.array(Image.open(mpath))
        uniq = np.unique(arr)
        print(f"  Mask {i} {os.path.basename(mpath)} -> {uniq[:20].tolist()}")
print("Peeking train masks:"); peek_mask_ids(train_pairs)
print("Peeking val masks:");   peek_mask_ids(val_pairs)

"""# Resize pad & transforms

"""

def resize_and_pad(img_pil: Image.Image, mask_pil: Image.Image, target_hw=(512, 384)):
    th, tw = target_hw
    w, h = img_pil.size
    scale = min(th / h, tw / w)
    nh, nw = int(round(h * scale)), int(round(w * scale))

    img_rs  = img_pil.resize((nw, nh), Image.BILINEAR)
    mask_rs = mask_pil.resize((nw, nh), Image.NEAREST)

    pad_h, pad_w = th - nh, tw - nw
    top, left = pad_h // 2, pad_w // 2

    new_img  = Image.new("RGB", (tw, th), (0, 0, 0))
    new_mask = Image.new("L",   (tw, th), 0)
    new_img.paste(img_rs,  (left, top))
    new_mask.paste(mask_rs,(left, top))
    return new_img, new_mask

def train_transform(img_pil: Image.Image, mask_pil: Image.Image):
    if random.random() < 0.5:
        img_pil  = TF.hflip(img_pil)
        mask_pil = TF.hflip(mask_pil)
    angle = random.uniform(-10, 10)
    img_pil  = TF.rotate(img_pil, angle, interpolation=InterpolationMode.BILINEAR, fill=0)
    mask_pil = TF.rotate(mask_pil, angle, interpolation=InterpolationMode.NEAREST,  fill=0)

    if random.random() < 0.7:
        s = random.uniform(0.85, 1.35)
        nw, nh = int(img_pil.width * s), int(img_pil.height * s)
        img_pil  = img_pil.resize((nw, nh), Image.BILINEAR)
        mask_pil = mask_pil.resize((nw, nh), Image.NEAREST)
    img_pil, mask_pil = resize_and_pad(img_pil, mask_pil, IMAGE_SIZE)
    if random.random() < 0.5:
        jitter = ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1, hue=0.02)
        img_pil = jitter(img_pil)
    img  = TF.to_tensor(img_pil)
    img  = TF.normalize(img, mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225])
    mask = torch.as_tensor(np.array(mask_pil, dtype=np.int64))
    return img, mask

def val_transform(img_pil: Image.Image, mask_pil: Image.Image):
    img_pil, mask_pil = resize_and_pad(img_pil, mask_pil, IMAGE_SIZE)
    img  = TF.to_tensor(img_pil)
    img  = TF.normalize(img, mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225])
    mask = torch.as_tensor(np.array(mask_pil, dtype=np.int64))
    return img, mask

"""# Dataset & DataLoaders"""

from torch.utils.data import Dataset, DataLoader

class FoodSegDataset(Dataset):
    def __init__(self, pairs: List[Tuple[str, str]], training: bool = True):
        self.pairs = pairs
        self.training = training
    def __len__(self): return len(self.pairs)
    def __getitem__(self, idx):
        ip, mp = self.pairs[idx]
        img  = Image.open(ip).convert("RGB")
        mask = Image.open(mp)  # single-channel class IDs
        if self.training:  img, mask = train_transform(img, mask)
        else:              img, mask = val_transform(img, mask)
        return img, mask

train_ds = FoodSegDataset(train_pairs, training=True)
val_ds   = FoodSegDataset(val_pairs,   training=False)

pin = torch.cuda.is_available()
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,
                          num_workers=NUM_WORKERS, pin_memory=pin, drop_last=False)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=NUM_WORKERS, pin_memory=pin, drop_last=False)
xb, yb = next(iter(train_loader))
print("Train batch -> images:", xb.shape, xb.dtype, "| masks:", yb.shape, yb.dtype)
print("Mask ID range in sample batch:", int(yb.min()), "to", int(yb.max()))

"""# Model"""

from transformers import SegformerConfig, SegformerForSemanticSegmentation

BACKBONE = "nvidia/segformer-b3-finetuned-ade-512-512"
IGNORE_INDEX = -100

id2label_int = {int(k): v for k, v in id2label.items()}
label2id = {v: k for k, v in id2label_int.items()}

print("Backbone:", BACKBONE)
print("NUM_CLASSES:", NUM_CLASSES, "| Example labels:", list(id2label_int.items())[:5])

"""# Config & model"""

import torch
from transformers import SegformerConfig, SegformerForSemanticSegmentation

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

config = SegformerConfig.from_pretrained(
    BACKBONE,
    num_labels=NUM_CLASSES,
    id2label=id2label_int,
    label2id=label2id,
    ignore_index=IGNORE_INDEX,
)

model = SegformerForSemanticSegmentation.from_pretrained(
    BACKBONE,
    config=config,
    ignore_mismatched_sizes=True
).to(device)


trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
total_params     = sum(p.numel() for p in model.parameters())
print(f"Params: {trainable_params/1e6:.2f}M trainable / {total_params/1e6:.2f}M total")

"""# Helper to upsample logits to target (H,W)

"""

import torch.nn.functional as F

def upsample_logits(logits, target):
    """
    logits: (B, C, h, w)
    target: (B, H, W)  -- label map
    returns logits_up: (B, C, H, W)
    """
    H, W = target.shape[-2], target.shape[-1]
    return F.interpolate(logits, size=(H, W), mode="bilinear", align_corners=False)

model.eval()
with torch.inference_mode():
    xb, yb = next(iter(train_loader))
    xb = xb.to(device); yb = yb.to(device)

    out = model(pixel_values=xb)
    logits = out.logits
    logits_up = upsample_logits(logits, yb)

print("Raw logits:", tuple(logits.shape))
print("Upsampled :", tuple(logits_up.shape))

import torch.nn.functional as F

def upsample_logits(logits, target):
    H, W = target.shape[-2], target.shape[-1]
    return F.interpolate(logits, size=(H, W), mode="bilinear", align_corners=False)

B, C, h, w = logits.shape
Hin, Win = yb.shape[-2:]
assert C == NUM_CLASSES, "Channel count (classes) mismatch."

logits_up = upsample_logits(logits, yb)
Hout, Wout = logits_up.shape[-2], logits_up.shape[-1]
print(f"Input size:  ({Hin}, {Win}) | Raw logits: ({h}, {w}) | Upsampled: ({Hout}, {Wout})")

assert (Hout, Wout) == (Hin, Win), "Upsampled logits must match label size."
print("Spatial alignment OK after upsampling.")

import math
import torch
from torch.optim import AdamW

EPOCHS       = 30
BASE_LR      = 6e-5
WEIGHT_DECAY = 0.01
IGNORE_INDEX = -100

optimizer = AdamW(model.parameters(), lr=BASE_LR, weight_decay=WEIGHT_DECAY)

# Polynomial LR decay: lr = base_lr * (1 - t/T)^power
class PolyLR(torch.optim.lr_scheduler._LRScheduler):
    def __init__(self, optimizer, max_iters, power=0.9, last_epoch=-1):
        self.max_iters = max_iters
        self.power = power
        super().__init__(optimizer, last_epoch)
    def get_lr(self):
        t = min(self.last_epoch, self.max_iters)
        factor = (1.0 - t / self.max_iters) ** self.power
        return [base_lr * factor for base_lr in self.base_lrs]

max_iters = EPOCHS * len(train_loader)
scheduler = PolyLR(optimizer, max_iters=max_iters, power=0.9)

scaler = torch.cuda.amp.GradScaler(enabled=torch.cuda.is_available())
device = next(model.parameters()).device

import numpy as np
import torch

@torch.no_grad()
def estimate_class_freq(loader, num_classes):
    counts = torch.zeros(num_classes, dtype=torch.long)
    for imgs, masks in loader:
        # masks: [B,H,W]
        counts += torch.bincount(masks.view(-1), minlength=num_classes)[:num_classes]
    freq = counts.float() / counts.sum().clamp_min(1)
    return counts, freq

counts, freq = estimate_class_freq(train_loader, NUM_CLASSES)
valid = freq > 0
median_f = freq[valid].median() if valid.any() else torch.tensor(1.0)
class_weights = (median_f / (freq + 1e-6)).clamp(max=50.0).to(device)

print("Class weight stats -> min:", float(class_weights.min()),
      "median:", float(class_weights.median()),
      "max:", float(class_weights.max()))

import torch.nn as nn
import torch.nn.functional as F

def upsample_logits(logits, target):
    H, W = target.shape[-2], target.shape[-1]
    return F.interpolate(logits, size=(H, W), mode="bilinear", align_corners=False)

class CEDiceLoss(nn.Module):
    def __init__(self, class_weights=None, smooth=1.0, ignore_index=-100):
        super().__init__()
        self.ce = nn.CrossEntropyLoss(weight=class_weights, ignore_index=ignore_index)
        self.smooth = smooth
        self.ignore_index = ignore_index
        self.class_weights = class_weights

    def forward(self, logits, target):
        logits = upsample_logits(logits, target)
        ce = self.ce(logits, target)

        # Dice on valid pixels
        with torch.no_grad():
            valid = target.ne(self.ignore_index)
        if valid.sum() == 0:
            return ce

        probs = F.softmax(logits, dim=1).permute(0,2,3,1)[valid]   # (V,C)
        tgt_oh = F.one_hot(target[valid], num_classes=logits.shape[1]).float()  # (V,C)

        inter = (probs * tgt_oh).sum(dim=0)                             # (C,)
        union = probs.sum(dim=0) + tgt_oh.sum(dim=0)                    # (C,)
        dice = (2*inter + self.smooth) / (union + self.smooth)          # (C,)

        if self.class_weights is not None:
            w = (self.class_weights / self.class_weights.sum()).detach()
            dice_loss = 1.0 - (dice * w).sum()
        else:
            dice_loss = 1.0 - dice.mean()

        return ce + 0.5 * dice_loss

criterion = CEDiceLoss(class_weights=class_weights, ignore_index=IGNORE_INDEX)

"""# Train / Val loop (with fixed GradScaler API

"""

import os
from pathlib import Path
import torch
import torch.nn.functional as F

# use new AMP API
scaler = torch.amp.GradScaler('cuda', enabled=torch.cuda.is_available())

def pixel_accuracy(pred, target, ignore_index=-100):
    mask = target.ne(ignore_index)
    correct = (pred.eq(target) & mask).sum().item()
    total   = mask.sum().item()
    return correct / max(total, 1)

@torch.no_grad()
def confusion_matrix(pred, target, num_classes, ignore_index=-100):
    mask = target.ne(ignore_index)
    pred = pred[mask]
    tgt  = target[mask]
    cm = torch.bincount(
        (tgt * num_classes + pred).view(-1),
        minlength=num_classes * num_classes
    ).reshape(num_classes, num_classes)
    return cm

def miou_from_confmat(cm):
    tp = cm.diag().float()
    fp = cm.sum(0).float() - tp
    fn = cm.sum(1).float() - tp
    denom = tp + fp + fn
    iou = torch.where(denom > 0, tp / denom.clamp_min(1), torch.zeros_like(tp))
    return float(iou.mean().item()), iou

CKPT_DIR = f"{ROOT}/segformer_b3_512x384_ckpts"
Path(CKPT_DIR).mkdir(parents=True, exist_ok=True)
best_miou = -1.0

EPOCHS = 3

for epoch in range(1, EPOCHS+1):
    # ---- train ----
    model.train()
    tr_loss = tr_pa = 0.0
    nb = 0
    for imgs, masks in train_loader:
        imgs  = imgs.to(device, non_blocking=True)
        masks = masks.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)
        with torch.amp.autocast('cuda', enabled=torch.cuda.is_available()):
            out = model(pixel_values=imgs)
            logits = out.logits
            loss = criterion(logits, masks)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        scheduler.step()

        with torch.no_grad():
            pred = F.interpolate(logits, size=masks.shape[-2:], mode="bilinear",
                                 align_corners=False).argmax(1)
            tr_pa += pixel_accuracy(pred, masks, ignore_index=IGNORE_INDEX)
        tr_loss += loss.item()
        nb += 1

    tr_loss /= max(nb, 1)
    tr_pa   /= max(nb, 1)

    # ---- validate ----
    model.eval()
    val_loss = val_pa = 0.0
    cm_total = torch.zeros(NUM_CLASSES, NUM_CLASSES, dtype=torch.long)
    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs  = imgs.to(device, non_blocking=True)
            masks = masks.to(device, non_blocking=True)
            with torch.amp.autocast('cuda', enabled=torch.cuda.is_available()):
                out = model(pixel_values=imgs)
                logits = out.logits
                loss = criterion(logits, masks)
            pred = F.interpolate(logits, size=masks.shape[-2:], mode="bilinear",
                                 align_corners=False).argmax(1)
            val_loss += loss.item()
            val_pa   += pixel_accuracy(pred, masks, ignore_index=IGNORE_INDEX)
            cm_total += confusion_matrix(pred.cpu(), masks.cpu(), NUM_CLASSES, ignore_index=IGNORE_INDEX)

    val_loss /= max(len(val_loader), 1)
    val_pa   /= max(len(val_loader), 1)
    val_miou, per_cls_iou = miou_from_confmat(cm_total)

    lr_now = scheduler.get_last_lr()[0]
    print(f"Epoch {epoch:02d} | train_loss {tr_loss:.4f} | train_PA {tr_pa:.3f} | "
          f"val_loss {val_loss:.4f} | val_PA {val_pa:.3f} | val_mIoU {val_miou:.3f} | lr {lr_now:.2e}")

    if val_miou > best_miou:
        best_miou = val_miou
        ckpt_path = os.path.join(CKPT_DIR, f"segformer_b3_best_miou_{best_miou:.3f}.pt")
        torch.save({
            "epoch": epoch,
            "model": model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "scheduler": scheduler.state_dict(),
            "best_miou": best_miou,
            "config": model.config.to_dict()
        }, ckpt_path)
        print(f"Saved new best to: {ckpt_path}")

import numpy as np
from torch.utils.data import WeightedRandomSampler
img_weights = []
for _, mask_path in train_pairs:
    arr = np.array(Image.open(mask_path), dtype=np.int64)
    ids = np.unique(arr)
    ids = ids[(ids >= 0) & (ids < NUM_CLASSES)]
    if ids.size == 0:
        img_weights.append(1.0); continue
    w = class_weights[torch.as_tensor(ids, device=class_weights.device)]
    img_weights.append(float(w.max().item()))

w_arr = np.array(img_weights, dtype=np.float64)
w_arr = w_arr / (w_arr.mean() + 1e-8)

sampler = WeightedRandomSampler(weights=w_arr, num_samples=len(train_pairs), replacement=True)

train_loader = DataLoader(
    train_ds,
    batch_size=BATCH_SIZE,
    sampler=sampler,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available(),
    drop_last=False,
)
print("Sampler ready. Weight stats -> min:", float(w_arr.min()),
      "mean:", float(w_arr.mean()), "max:", float(w_arr.max()))

current_lr = scheduler.get_last_lr()[0]
for pg in optimizer.param_groups:
    pg["lr"] = current_lr

EXTRA_EPOCHS = 5
max_iters = EXTRA_EPOCHS * len(train_loader)
scheduler = type(scheduler)(optimizer, max_iters=max_iters, power=0.9)

def pixel_accuracy(pred, target, ignore_index=-100):
    mask = target.ne(ignore_index)
    correct = (pred.eq(target) & mask).sum().item()
    total   = mask.sum().item()
    return correct / max(total, 1)

best_miou_so_far = best_miou if 'best_miou' in globals() else -1.0

import torch.nn.functional as F
import os

for e in range(1, EXTRA_EPOCHS + 1):
    model.train()
    tr_loss, tr_pa, nb = 0.0, 0.0, 0

    for imgs, masks in train_loader:
        imgs  = imgs.to(device, non_blocking=True)
        masks = masks.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)
        with torch.amp.autocast('cuda', enabled=torch.cuda.is_available()):
            out = model(pixel_values=imgs)
            logits = out.logits
            loss = criterion(logits, masks)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        scheduler.step()

        with torch.no_grad():
            pred = F.interpolate(logits, size=masks.shape[-2:], mode="bilinear",
                                 align_corners=False).argmax(1)
            tr_pa += pixel_accuracy(pred, masks, ignore_index=IGNORE_INDEX)

        tr_loss += loss.item()
        nb += 1

    tr_loss /= max(nb, 1)
    tr_pa   /= max(nb, 1)

    # ------------ Validate ------------
    model.eval()
    val_loss, val_pa = 0.0, 0.0
    cm_total = torch.zeros(NUM_CLASSES, NUM_CLASSES, dtype=torch.long, device="cpu")

    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs  = imgs.to(device, non_blocking=True)
            masks = masks.to(device, non_blocking=True)

            with torch.amp.autocast('cuda', enabled=torch.cuda.is_available()):
                out = model(pixel_values=imgs)
                logits = out.logits
                loss = criterion(logits, masks)

            pred = F.interpolate(logits, size=masks.shape[-2:], mode="bilinear",
                                 align_corners=False).argmax(1)

            val_loss += loss.item()
            val_pa   += pixel_accuracy(pred, masks, ignore_index=IGNORE_INDEX)

            # confusion matrix on CPU to avoid device mismatch
            m = masks.view(-1)
            p = pred.view(-1)
            valid = m.ne(IGNORE_INDEX)
            m = m[valid].detach().to("cpu")
            p = p[valid].detach().to("cpu")

            cm_total += torch.bincount(
                (m * NUM_CLASSES + p).view(-1),
                minlength=NUM_CLASSES * NUM_CLASSES
            ).reshape(NUM_CLASSES, NUM_CLASSES)

    val_loss /= max(len(val_loader), 1)
    val_pa   /= max(len(val_loader), 1)

    # mIoU from confusion matrix
    tp = cm_total.diag().float()
    fp = cm_total.sum(0).float() - tp
    fn = cm_total.sum(1).float() - tp
    denom = tp + fp + fn
    iou = torch.where(denom > 0, tp / denom.clamp_min(1), torch.zeros_like(tp))
    val_miou = float(iou.mean().item())

    print(f"[Oversample] Epoch {e:02d} | train_loss {tr_loss:.4f} | train_PA {tr_pa:.3f} | "
          f"val_loss {val_loss:.4f} | val_PA {val_pa:.3f} | val_mIoU {val_miou:.3f} | "
          f"lr {scheduler.get_last_lr()[0]:.2e}")

    # save best
    if val_miou > best_miou_so_far:
        best_miou_so_far = val_miou
        ckpt_path = os.path.join(ROOT, "segformer_b3_512x384_ckpts",
                                 f"segformer_b3_best_miou_{best_miou_so_far:.3f}.pt")
        torch.save(
            {"model": model.state_dict(),
             "best_miou": best_miou_so_far,
             "config": model.config.to_dict()},
            ckpt_path
        )
        print(f"Saved new best (mIoU={best_miou_so_far:.3f}) → {ckpt_path}")

"""# EMA helper

"""

class EMA:
    def __init__(self, model, decay=0.999):
        self.decay = decay
        self.shadow = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

    @torch.no_grad()
    def update(self, model):
        for k, v in model.state_dict().items():
            if v.dtype.is_floating_point:
                self.shadow[k].mul_(self.decay).add_(v.detach().cpu(), alpha=1 - self.decay)
            else:
                self.shadow[k] = v.detach().cpu().clone()

    @torch.no_grad()
    def apply_to(self, model):
        device = next(model.parameters()).device
        ema_state = {k: v.to(device) for k, v in self.shadow.items()}
        model.load_state_dict(ema_state, strict=False)

ema = EMA(model, decay=0.999)
print("EMA ready (decay=0.999).")

"""# Train more with EMA

"""

import copy
import torch.nn.functional as F
import os

EXTRA_EPOCHS = 8

current_lr = scheduler.get_last_lr()[0]
for pg in optimizer.param_groups:
    pg["lr"] = current_lr

max_iters = EXTRA_EPOCHS * len(train_loader)
scheduler = type(scheduler)(optimizer, max_iters=max_iters, power=0.9)

for e in range(1, EXTRA_EPOCHS + 1):
    # ---------- Train ----------
    model.train()
    tr_loss = tr_pa = 0.0; nb = 0

    for imgs, masks in train_loader:
        imgs  = imgs.to(device, non_blocking=True)
        masks = masks.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)
        with torch.amp.autocast('cuda', enabled=torch.cuda.is_available()):
            out = model(pixel_values=imgs)
            logits = out.logits
            loss = criterion(logits, masks)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        scheduler.step()

        # update EMA after optimizer step
        ema.update(model)

        with torch.no_grad():
            pred = F.interpolate(logits, size=masks.shape[-2:], mode="bilinear",
                                 align_corners=False).argmax(1)
            tr_pa += (pred.eq(masks).sum().item() / masks.numel())
        tr_loss += loss.item(); nb += 1

    tr_loss /= max(nb,1); tr_pa /= max(nb,1)

    model_ema = copy.deepcopy(model).to(device)
    ema.apply_to(model_ema)
    model_ema.eval()

    val_loss = val_pa = 0.0
    cm_total = torch.zeros(NUM_CLASSES, NUM_CLASSES, dtype=torch.long, device="cpu")

    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs  = imgs.to(device, non_blocking=True)
            masks = masks.to(device, non_blocking=True)
            with torch.amp.autocast('cuda', enabled=torch.cuda.is_available()):
                out = model_ema(pixel_values=imgs)
                logits = out.logits
                loss = criterion(logits, masks)
            pred = F.interpolate(logits, size=masks.shape[-2:], mode="bilinear",
                                 align_corners=False).argmax(1)

            val_loss += loss.item()
            val_pa   += (pred.eq(masks).sum().item() / masks.numel())

            # confusion matrix on CPU
            m = masks.view(-1); p = pred.view(-1)
            valid = m.ne(IGNORE_INDEX)
            m = m[valid].detach().to("cpu"); p = p[valid].detach().to("cpu")
            cm_total += torch.bincount(
                (m * NUM_CLASSES + p).view(-1),
                minlength=NUM_CLASSES * NUM_CLASSES
            ).reshape(NUM_CLASSES, NUM_CLASSES)

    val_loss /= max(len(val_loader), 1)
    val_pa   /= max(len(val_loader), 1)
    tp = cm_total.diag().float(); fp = cm_total.sum(0).float() - tp; fn = cm_total.sum(1).float() - tp
    denom = tp + fp + fn
    iou = torch.where(denom > 0, tp / denom.clamp_min(1), torch.zeros_like(tp))
    val_miou = float(iou.mean().item())

    print(f"[EMA] Epoch {e:02d} | train_loss {tr_loss:.4f} | train_PA {tr_pa:.3f} | "
          f"val_loss {val_loss:.4f} | val_PA {val_pa:.3f} | val_mIoU {val_miou:.3f} | "
          f"lr {scheduler.get_last_lr()[0]:.2e}")

    # save best EMA checkpoint
    if val_miou > best_miou_so_far:
        best_miou_so_far = val_miou
        ckpt_path = os.path.join(ROOT, "segformer_b3_512x384_ckpts",
                                 f"segformer_b3_best_miou_EMA_{best_miou_so_far:.3f}.pt")
        torch.save(
            {"model": model_ema.state_dict(),  # save EMA weights
             "best_miou": best_miou_so_far,
             "config": model.config.to_dict()},
            ckpt_path
        )
        print(f"Saved new EMA best (mIoU={best_miou_so_far:.3f}) → {ckpt_path}")

val_miou = [0.397, 0.412, 0.421, 0.428, 0.434, 0.438, 0.441, 0.444]
val_pacc = [0.819, 0.826, 0.832, 0.836, 0.839, 0.841, 0.842, 0.844]
val_loss = [1.874, 2.021, 2.155, 2.249, 2.291, 2.335, 2.374, 2.424]

epochs = range(1, 9)

plt.plot(epochs, val_miou, marker='o', label="Val mIoU")
plt.xlabel("Epoch")
plt.ylabel("mIoU")
plt.title("Validation mIoU over Epochs")
plt.legend()
plt.show()